# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'cosmosdbsj'
  imageRepository: 'cosmosdbsj'
  containerRegistry: cosmosdbsj.azurecr.io
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  tag: $(Build.BuildId)
  appName: CosmosDBsj

    # - task: AzureWebAppContainer@1
    #   inputs:
    #     azureSubscription: RMPM
    #     appName: dsdidshdsdsn
    #     containers: $(containerRegistry)/$(imageRepository):$(tag)
