# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

        tags: |
          $(tag)
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: cosmosdbsj
        appName: CosmosDBsj
        containers: $(containerRegistry)/$(imageRepository):$(tag)
    # - task: AzureWebAppContainer@1
    #   inputs:
    #     azureSubscription: RMPM
    #     appName: dsdidshdsdsn
    #     containers: $(containerRegistry)/$(imageRepository):$(tag)
