variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: cosmosdbsj
  imageRepository: contoso
  containerRegistry: contoso.azurecr.io
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  tag: $(Build.BuildId)
  appName: cosmosdbsj
